version: '2'
services:
  dns:
    restart: always
    image: strm/dnsmasq
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
      - ./hosts-dnsmasq2:/etc/hosts-dnsmasq
    ports:
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
