version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    ports:
      - 8443:8443
      - 8081:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
